name: first Github actions

on: [push]

jobs:
  build:
    runs_on: ubuntu-latest

    stratergy:
      matrix:
        python-version: [3.8,3.9]

    steps:
      - uses: actions/checkour@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Installing all the dependencies
        run: 
          python -m pip install --upgrade pip
          pip install pytest

      - name: Running tests
        run:
          python -m pytest addition.py